### ISSUE TITLE
Remove SharedLink error

### ISSUE THREAD

**Issue by FlorientR** [Schmidt-DevOps/Seafile-PHP-SDK#23]
### Expected behaviour
Remove a shared link

### Actual behaviour
Exception

### Steps to reproduce the behaviour
```
$oSharedLink = new Seafile\Client\Resource\SharedLink($this->oClient);
$aLinks = $oSharedLink->getAll();
		
foreach ($aLinks as $oSharedLinkType)
{
	if ($oSharedLinkType->path == $sCustomerPath)
	{
		//$oSharedLinkType->url = $oSharedLinkType->token;
		$oSharedLink->remove($oSharedLinkType);
		break;
	}
}
```
#### Which call are you making?
Remove Shared Link

#### Do you have permissions to create a new directory?
Yes

#### Do you have permissions to read the directory?
Yes

#### Does the Seafile server work OK otherwise?
Yes

#### Did you obtain an API token from the server and has it been stored correctly?
Yes

#### Which branch or tag of the Seafile-PHP-SDK are you using?
Latest

#### Which PHP version are you using?
7.2

#### What is the version of the Seafile server you are using?
6.x

#### Is the OS you are using Seafile-PHP-SDK on 32 bits or 64 bits?
64 bits

#### Are there error messages in the Seafile server's log files? If so, please post them.
No

Hi,
I want remove a shared link so I get all links and I search my link. When I found my link, I remove the link with SharedLink->remove(SharedLinkType). But I have an exception beacause the "url" field on SharedLinkType is null. It's the "url" field that used for "t=" link instead of "token".

I have add SharedLinkType->url = SharedLinkType->token before remove and all it's ok. It's due to my 6.x version server ?

Buy,
Flo

**Comment by rene-s** [comment]
Hello Flo, thanks for reporting this issue. Unfortunately I cannot reproduce the error with Seafile Server 6.x as I do not run or support that version any more. Please retry with Seafile Server 7.1.4 once you have that version available (you had mentioned you are still bound to 6.x yet) and if the issue is reproducible please report back with a new issue so I can investigate further. Thank you very much!

Regards
Rene
