### ISSUE TITLE
Download directory: Is it possible to download full directory?

### ISSUE THREAD

**Issue by bjarneoehmke** [Schmidt-DevOps/Seafile-PHP-SDK#25]
Hey,

thanks for creating this nice SDK.

Is it possible to get a download URL for a directory?

Thanks,
Bjarne

**Comment by rene-s** [comment]
Hello Bjarne, thanks for your message. While it is certainly possible to use this SDK to download a whole directory, the SDK is supposed to mimic Seafile's REST API without adding abstraction. Because Seafile's REST API does not provide a high(er) level API function that lets you download a whole directory the PHP SDK does not either.

The best approach for you in my opinion would be to create a library that sits on top of the PHP SDK and that provides this abstraction:
1. Get the contents of a directory.
1. Download the files.
1. Handle recursion for sub directories.
1. Go to 1 unless done.

Hope that helps
Regards
