### ISSUE TITLE
getDownloadUrl (seems to) ignore my non-standard port.

### ISSUE THREAD

**Issue by lachlan-00** [Schmidt-DevOps/Seafile-PHP-SDK#33]
hey,
I'm just working on some issues in https://github.com/ampache/ampache/issues/3085 and i've set up a seafile server on port 8282 

* The base_uri gets set with the full url (`http://192.168.1.12:8282`)
* And then calls getDownloadUrl
* The url tries to download without the port `http://192.168.1.12/seafhttp/files/70c303d9-1776-4580-9b06-9c9cf3/Adagio.mp3`

I can't see any code in that's trimming the port off here or in Ampache but i just thought i'd check that a non-standard port is allowed.

**Comment by rene-s** [comment]
I agree, the port should not get cut. On the other hand it might be that `\GuzzleHttp\Client::getConfig` omits the port because Guzzle expects the port to be configured separately. Maybe have a look in that direction. Either way, using `\GuzzleHttp\Client::getConfig` is deprecated anyhow, so I will need to update the code in that regard. Then I will take care of handling non-standard ports too.
